version: '2'
services:
  server:
    image: desyncr/accounting-server
    ports:
     - "8080:8080"
  api:
    image: desyncr/accounting-api
    ports:
     - "4567:4567"
    environment:
        - CLIENT_HOST=server
  client:
    image: desyncr/accounting-api-client
    ports:
     - "8000:80"
